name: Release

on:
  push:
    branches: [ "main", "develop" ]
    tags: [ 'v*.*.*' ]

env:
  commit_msg: ${{ github.event.head_commit.message }}


jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: write

    steps:
      - name: Setup yq
        run: sudo snap install yq

      - name: Install yarn dependencies
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 22
      - name: Build html
        run: ./bin/compile-html
      - name: Archive html
        run: zip -r html.zip build/*
      - name: Release project
        uses: CupOfTea696/gh-action-auto-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload build to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: html.zip
